### PR TITLE
Added ambilight to address #180

### PR DESCRIPTION
**Pull request by DarthAffe**
I think it looks quite ok like this.
New types/algorithms of calculating the lighting can easily be added by implementing 'IAmbienceCreator'.

Performance seems to be fine too: A profile only containing one layer of ambilight with default settings causes 1-2% CPU-load on my PC (i7-2600K). It doesn't seem to leak memory, but I'm currently running a long time check.

Please look over it and feel free to criticize or ask if there is something you don't like :)

### CODE REVIEW

**Comment by SpoinkyNL** [comment]
Hey man, that's really impressive :o
Love the amount of options available, it works well and the code looks clean 👍. 

One thing I noticed which may not be fixable is the CPU usage on 4k, it's hovering at around 18% on my i5-6600k, RAM is steady though.

I don't think it can be avoided having the CPU usage go up at such an immense resolution, but if there's a way to downscale the samples you're taking it might help, if not I'm happy to merge it in the way it is, 4k isn't widely used and people that do know that it takes a huge toll.

**Comment by SpoinkyNL** [comment]
Did a bit of profiling and it seems to mainly come from  _device.GetFrontBufferData(0, _surface); in DX9ScreenCapture which was to be expected: http://i.imgur.com/Oe5s7q9.png

Perhaps it would be worth adding a update/second option to decrease the sample rate (update rate can stay the same I reckon, so color transitions will stay smooth)

**Comment by DarthAffe** [comment]
> Perhaps it would be worth adding a update/second option to decrease the sample rate (update rate can stay the same I reckon, so color transitions will stay smooth)

This option exists [ScreenCaptureManager.UpdateRate](https://github.com/DarthAffe/Artemis/blob/development/Artemis/Artemis/Profiles/Layers/Types/AmbientLight/ScreenCapturing/ScreenCaptureManager.cs#L18)
But since this isn't a layer-option but one that affects all ambilight-layers I decided not to add it to the options.
I think quite a big performance gain would be also possible, if I'd implement a DX10/DX11 ScreenCapture too, since the performance of readbacks is told to be greatly improved there. But this should be also selectable for backward compatibility.

Downsampling while processing is possible (and already done by a factor of 2), I'll add a option to increase this a bit.

**Comment by SpoinkyNL** [comment]
Ah yes I tried setting the update rate to 5, it still looks pretty good to me but that's unnecessary for 1080p of course. It could be added as a program-wide option, or an auto-adjust that measures how long each call takes and scales down accordingly

**Comment by DarthAffe** [comment]
Adaptive capturing would require a "performance-target". I think it's easier to just add an option. Is it ok to just add it at the bottom (above the buttons) of the settings-flyout?

Regarding DX10 capturing: I think this would worth quite much but I can't implement it since Desktop-Duplication doesn't work prior Windows 8.1. (I'm still using 7)
The code you linked in the issue was using this technique if I remember correctly.

**Comment by SpoinkyNL** [comment]
Yes a setting in the flyout is fine 👍 

I can have a peek at DX10 capturing in the future but I think what you've got here is already well worth releasing

**Comment by DarthAffe** [comment]
Could you test the 4K again? I think settings like Capture FPS 10 and downsampling 4 should be ok.

**Comment by SpoinkyNL** [comment]
Looks good, downsampling as far as 8 gave me 10% usage on 10 FPS, 5 FPS 5% etc.

The capturer also disables itself properly when layer conditions aren't met/the profile is deactivated, so in the future we could create a condition allowing users to only it when a video player is running full screen or something like that.

**Pull request merged**
