### PR TITLE
Added the new Overwatch Characters and added initial implementation of LuaSlider.

### PR DESCRIPTION
**Pull request by TylerJaacks**
Added Orisa and Doomfist to the OverwatchCharacter, and added Orisa and Doomfist to CharacterColor in OverwatchModel. Also created the LuaSlider class and added the initial implementation. LuaSlider is missing the event system.

### CODE REVIEW

**Comment by SpoinkyNL** [comment]
Hey there, looks great, thanks I'll test these out tomorrow!

Project seems a bit inactive atm but I still have plans and ideas for the future. I have the time to work on it again as well

**Comment by TylerJaacks** [comment]
For some reason I couldn't get the Slider Event System working I might take a look at it later. Also going to do some digging into adding iTunes support and adding some games that are on the issue list.

**Comment by SpoinkyNL** [comment]
Hi there,
I had to adjust the colors in the Overwatch module. The module only uses these colors to determine what character you currently have selected, not actually to change the color of the connected devices (that's done in the profile). 

With the LUA slider you already had most of it right, I added the event and hooked it up to LUA. Also sliders need a minimum and maximum value to function so I added those as well.

Lastly I figured sliders work nicer with ticks, else you get very precise values such as 6.9999991 so I enabled them.

Please have a look at the commit and let me know what you think

**Comment by TylerJaacks** [comment]
I looked at the commit and looks good, will I get credited for this change, since you didn't merge it?

**Comment by SpoinkyNL** [comment]
Sorry for slack, yeah you'll get credit of course :)

**Comment by TylerJaacks** [comment]
Thank you!

**Pull request merged**
