### PR TITLE
Added Bouncing-Bubbles-Effect

### PR DESCRIPTION
**Pull request by DarthAffe**
I just tried how to create an own effect. Nothing too fancy but I like the windows bubble-screensaver and now it's on the keyboard too :)

### CODE REVIEW

**Comment by SpoinkyNL** [comment]
Very cool stuff, thanks :+1:

**Comment by SpoinkyNL** [comment]
I had to disable it for now in Artemis, it looks really cool but it causes around 20% CPU usage and huge RAM spikes :(

**Comment by DarthAffe** [comment]
Oh, I'll investigate this. It seems like the problem is the high scale-factor I use. If I set the AudioVisualizer to the same value the behavior is the same.

**Comment by DarthAffe** [comment]
Yep, the memory thing is because of leaking bitmaps - I fixed that for my effect but it might be better to apply a fix like this to the loopmanager instead - now for the high cpu usage :p

**Pull request merged**
